[workspace]
members = ["programs/charityblock"]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/charityblock.json"

[programs.devnet]
charityblock = "7zkgjDgZReMvhMuJtMU6Rx9ijsqKVpCH1sf6GcCp2dnW"

[toolchain]
anchor_version = "0.31.1"
