name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Use the official Solana toolchain image (has solana + cargo-build-sbf preinstalled)
    container:
      image: ghcr.io/anza-xyz/solana:1.18.20

    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Show toolchain
        shell: bash
        run: |
          set -eux
          solana --version
          which cargo-build-sbf || true
          cargo-build-sbf --version || true
          rustc -V || true
          cargo -V || true

      - name: Install Anchor 0.31.1 via AVM
        shell: bash
        run: |
          set -eux
          curl -fsSL https://raw.githubusercontent.com/coral-xyz/anchor/master/avm/install.sh | bash
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          avm install 0.31.1
          avm use 0.31.1
          anchor --version

      - name: Build Program
        env:
          ANCHOR_WALLET: ${{ github.workspace }}/target/deploy/charityblock-keypair.json
        shell: bash
        run: |
          set -eux
          anchor clean
          anchor build
          ls -la target/deploy
          ls -la target/idl

      - uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/deploy/charityblock.so
            target/deploy/charityblock-keypair.json
            target/idl/charityblock.json
