name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Modern Rust (Cargo lock v4 support)
      - name: Rust toolchain 1.86.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: rustfmt, clippy

      # ---- Solana 1.18.20 with mirror fallback ----
      - name: Install Solana 1.18.20 (with fallback)
        shell: bash
        run: |
          set -eux
          SOLANA_VER=v1.18.20
          MIRROR1="https://github.com/solana-labs/solana/releases/download/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
          MIRROR2="https://release.solana.com/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"

          for URL in "$MIRROR1" "$MIRROR2"; do
            if curl -fL --retry 3 --retry-delay 2 -o /tmp/sol.tar.bz2 "$URL"; then
              echo "Downloaded from $URL"
              break
            fi
          done

          mkdir -p /tmp/sol-release
          tar -xjf /tmp/sol.tar.bz2 -C /tmp/sol-release

          mkdir -p "$HOME/solana-release/bin"
          cp -a /tmp/sol-release/solana-release/bin/* "$HOME/solana-release/bin"

          echo "$HOME/solana-release/bin" >> "$GITHUB_PATH"
          solana --version

      # ---- Install AVM via Cargo, then Anchor 0.31.1 (use shim on PATH) ----
      - name: Install AVM and Anchor 0.31.1
        shell: bash
        run: |
          set -eux
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 avm --locked
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

          avm --version
          avm install 0.31.1
          avm use 0.31.1

          # Only the shim dir is needed; it resolves the selected version.
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"

          anchor --version
          # Use the shim for later steps
          echo "ANCHOR_BIN=anchor" >> "$GITHUB_ENV"

      # Safety: ensure no stale lockfiles
      - name: Remove Cargo.lock files
        shell: bash
        run: |
          set -eux
          find . -name Cargo.lock -delete

      - name: Show toolchain
        shell: bash
        run: |
          rustc -V
          cargo -V
          anchor --version
          solana --version

      - name: Build Program
        shell: bash
        run: |
          set -eux
          "$ANCHOR_BIN" clean
          "$ANCHOR_BIN" build

      - name: Upload IDL and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/idl/**
            target/deploy/**
            target/types/**