name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUSTUP_TOOLCHAIN: "1.86.0"
      ANCHOR_RUSTC_VERSION: "1.86.0"  # <-- Forces Anchor to use this Rust toolchain internally

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Rust 1.86.0 ---
      - name: Install Rust 1.86.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: rustfmt, clippy

      # --- Solana 1.18.20 ---
      - name: Install Solana 1.18.20 (with fallback)
        shell: bash
        run: |
          set -eux
          SOLANA_VER=v1.18.20
          MIRROR1="https://github.com/solana-labs/solana/releases/download/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
          MIRROR2="https://release.solana.com/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"

          OK=0
          for URL in "$MIRROR1" "$MIRROR2"; do
            if curl -fL --retry 3 --retry-delay 2 -o /tmp/sol.tar.bz2 "$URL"; then
              echo "Downloaded from $URL"
              OK=1
              break
            fi
            sleep 2
          done
          if [ "$OK" -ne 1 ]; then
            echo "Failed to download Solana ${SOLANA_VER} from all mirrors" >&2
            exit 1
          fi

          mkdir -p /tmp/sol-release
          tar -xjf /tmp/sol.tar.bz2 -C /tmp/sol-release

          mkdir -p "$HOME/solana-release/bin"
          cp -a /tmp/sol-release/solana-release/bin/* "$HOME/solana-release/bin"

          echo "$HOME/solana-release/bin" >> "$GITHUB_PATH"
          "$HOME/solana-release/bin/solana" --version

      # --- Anchor 0.31.1 ---
      - name: Install AVM and Anchor 0.31.1
        shell: bash
        run: |
          set -eux
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 avm --locked
          avm install 0.31.1
          avm use 0.31.1
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          anchor --version
          echo "ANCHOR_BIN=anchor" >> "$GITHUB_ENV"

      # --- Ensure correct cargo path + remove stale locks ---
      - name: Prepare environment
        shell: bash
        run: |
          set -eux
          rustup default 1.86.0
          which cargo
          cargo -V
          find . -name Cargo.lock -delete

      - name: Build Program
        shell: bash
        run: |
          set -eux
          echo "Using toolchain:"
          rustup show
          cargo -V
          $ANCHOR_BIN clean
          $ANCHOR_BIN build

      - name: Upload IDL and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/idl/**
            target/deploy/**
            target/types/**