name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Modern Rust so Cargo understands lockfile v4
      - name: Rust toolchain 1.86.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: rustfmt, clippy

      - name: Use Rust 1.86 globally
        shell: bash
        run: |
          set -eux
          rustup default 1.86.0
          rustup override set 1.86.0
          rustc -V
          cargo -V
      # Install Solana CLI 1.18.20 using the install-init binary from the release
      - name: Install Solana 1.18.20 (install-init)
        shell: bash
        run: |
          set -eux
          SOLANA_VER=v1.18.20
          INIT_URL="https://github.com/anza-xyz/solana/releases/download/${SOLANA_VER}/solana-install-init-x86_64-unknown-linux-gnu"

          # Download the init binary with retries
          for i in 1 2 3 4 5; do
            curl -fL --retry 3 --retry-delay 2 -o /tmp/solana-install-init "$INIT_URL" && break || sleep 3
          done

          chmod +x /tmp/solana-install-init
          /tmp/solana-install-init -v "$SOLANA_VER" -y

          # Add Solana to PATH
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"

          solana --version
          which cargo-build-sbf
      
      # Install Anchor CLI 0.31.1 via AVM
      - name: Install Anchor CLI 0.31.1
        shell: bash
        run: |
          set -eux
          curl -fsSL https://raw.githubusercontent.com/coral-xyz/anchor/master/avm/install.sh | bash
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          avm install 0.31.1
          avm use 0.31.1
          anchor --version

      # Safety: remove incompatible lockfiles
      - name: Remove Cargo.lock files
        shell: bash
        run: |
          set -eux
          find . -name Cargo.lock -delete

      - name: Show toolchain
        shell: bash
        run: |
          rustc -V
          cargo -V
          anchor --version
          solana --version
          which cargo-build-sbf

      - name: Build Program
        env:
          RUSTUP_TOOLCHAIN: 1.86.0
        shell: bash
        run: |
          set -eux
          anchor clean
          anchor build

      - name: Upload IDL and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/idl/**
            target/deploy/**
            target/types/**