name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Modern Rust (Cargo understands lockfile v4)
      - name: Rust toolchain 1.86.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: rustfmt, clippy

      # --- Solana 1.18.20 (working mirror logic) ---
      - name: Install Solana 1.18.20 (with fallback)
        shell: bash
        run: |
          set -eux
          SOLANA_VER=v1.18.20
          MIRROR1="https://github.com/solana-labs/solana/releases/download/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
          MIRROR2="https://release.solana.com/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"

          for URL in "$MIRROR1" "$MIRROR2"; do
            if curl -fL --retry 3 --retry-delay 2 -o /tmp/sol.tar.bz2 "$URL"; then
              echo "Downloaded solana from $URL"
              break
            fi
          done

          mkdir -p /tmp/sol-release
          tar -xjf /tmp/sol.tar.bz2 -C /tmp/sol-release

          mkdir -p "$HOME/solana-release/bin"
          cp -a /tmp/sol-release/solana-release/bin/* "$HOME/solana-release/bin"

          echo "$HOME/solana-release/bin" >> "$GITHUB_PATH"
          "$HOME/solana-release/bin/solana" --version

      # --- FIX: install AVM via Cargo, then Anchor 0.31.1 via AVM ---
      - name: Install AVM and Anchor 0.31.1
        shell: bash
        run: |
          set -eux
          # Build AVM from the Anchor repo at the 0.31.1 tag
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 avm --locked
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

          avm --version
          avm install 0.31.1
          avm use 0.31.1
          ~/.avm/bin/anchor --version

      # Safety: let Anchor regenerate any lockfiles
      - name: Remove Cargo.lock files
        shell: bash
        run: |
          set -eux
          find . -name Cargo.lock -delete

      - name: Show toolchain
        shell: bash
        run: |
          rustc -V
          cargo -V
          ~/.avm/bin/anchor --version
          solana --version

      - name: Build Program
        shell: bash
        run: |
          set -eux
          ~/.avm/bin/anchor clean
          ~/.avm/bin/anchor build

      - name: Upload IDL and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/idl/**
            target/deploy/**
            target/types/**