name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # Correct inputs: version, base_url (NOT solana-version)
      - name: Install Solana 1.18.20
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: "1.18.20"
          base_url: "https://release.anza.xyz"
          cache: true

      - name: Ensure Solana in PATH and show toolchain
        shell: bash
        run: |
          set -eux
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          solana --version
          which cargo-build-sbf || true
          cargo-build-sbf --version || true

      - name: Install Anchor via AVM (0.31.1)
        shell: bash
        run: |
          set -eux
          curl -fsSL https://raw.githubusercontent.com/coral-xyz/anchor/master/avm/install.sh | bash
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          avm install 0.31.1
          avm use 0.31.1
          anchor --version

      - name: Build Program
        env:
          ANCHOR_WALLET: ${{ github.workspace }}/target/deploy/charityblock-keypair.json
        shell: bash
        run: |
          set -eux
          anchor clean
          anchor build
          ls -la target/deploy
          ls -la target/idl

      - uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/deploy/charityblock.so
            target/deploy/charityblock-keypair.json
            target/idl/charityblock.json
