name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install a modern Rust that supports lockfile v4
      - name: Rust toolchain 1.86.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: rustfmt, clippy

      # Make 1.86 the active toolchain everywhere (anchor/cargo use it too)
      - name: Use Rust 1.86 globally
        shell: bash
        run: |
          set -eux
          rustup default 1.86.0
          rustup override set 1.86.0
          rustc -V
          cargo -V

      # Install Solana CLI 1.18.20
      - name: Install Solana 1.18.20
        shell: bash
        run: |
          set -eux
          curl -fsSL https://release.solana.com/v1.18.20/install -o /tmp/solana-install.sh
          bash /tmp/solana-install.sh -y
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          solana --version

      # Install Anchor CLI 0.31.1 via AVM (correct raw URL)
      - name: Install Anchor CLI 0.31.1
        shell: bash
        run: |
          set -eux
          curl -fsSL https://raw.githubusercontent.com/coral-xyz/anchor/master/avm/install.sh | bash
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          avm install 0.31.1
          avm use 0.31.1
          anchor --version

      # Safety: nuke any incompatible lockfiles
      - name: Remove Cargo.lock files
        shell: bash
        run: |
          set -eux
          find . -name Cargo.lock -delete

      # Optional: print toolchain summary
      - name: Show toolchain
        shell: bash
        run: |
          rustc -V
          cargo -V
          anchor --version
          solana --version

      # Build the program using the pinned toolchain
      - name: Build Program
        env:
          RUSTUP_TOOLCHAIN: 1.86.0
        shell: bash
        run: |
          set -eux
          anchor clean
          anchor build

      # Upload built artifacts
      - name: Upload IDL and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/idl/**
            target/deploy/**
            target/types/**