name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Keep host cargo/rust modern (v4 lockfile capable)
      RUSTUP_TOOLCHAIN: "1.86.0"
      ANCHOR_RUSTC_VERSION: "1.86.0"
      # Make rustup/cargo non-interactive in CI
      RUSTUP_NONINTERACTIVE: "1"
      CI: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust 1.86.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.86.0"
          components: rustfmt, clippy

      # ---- Solana 1.18.20 with mirror fallback ----
      - name: Install Solana 1.18.20 (with fallback)
        shell: bash
        run: |
          set -eux
          SOLANA_VER=v1.18.20
          MIRROR1="https://github.com/solana-labs/solana/releases/download/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
          MIRROR2="https://release.solana.com/${SOLANA_VER}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"

          OK=0
          for URL in "$MIRROR1" "$MIRROR2"; do
            if curl -fL --retry 3 --retry-delay 2 -o /tmp/sol.tar.bz2 "$URL"; then
              echo "Downloaded from $URL"
              OK=1; break
            fi
            sleep 2
          done
          if [ "$OK" -ne 1 ]; then
            echo "Failed to download Solana ${SOLANA_VER} from all mirrors" >&2
            exit 1
          fi

          mkdir -p /tmp/sol-release
          tar -xjf /tmp/sol.tar.bz2 -C /tmp/sol-release
          mkdir -p "$HOME/solana-release/bin"
          cp -a /tmp/sol-release/solana-release/bin/* "$HOME/solana-release/bin"

          echo "$HOME/solana-release/bin" >> "$GITHUB_PATH"
          "$HOME/solana-release/bin/solana" --version

      # ---- AVM + Anchor 0.31.1 (via cargo) ----
      - name: Install AVM and Anchor 0.31.1
        shell: bash
        run: |
          set -eux
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 avm --locked
          avm install 0.31.1
          avm use 0.31.1
          echo "$HOME/.avm/bin" >> "$GITHUB_PATH"
          anchor --version
          echo "ANCHOR_BIN=anchor" >> "$GITHUB_ENV"

      # ---- Clean stale lockfiles ----
      - name: Remove Cargo.lock files
        shell: bash
        run: |
          set -eux
          find . -name Cargo.lock -delete

      # ---- Generate v3 Cargo.lock using cargo 1.75.0 ----
      - name: Seed v3 Cargo.lock with Cargo 1.75.0
        shell: bash
        run: |
          set -eux
          # Correct syntax (no invalid -y placement)
          rustup toolchain install 1.75.0 --profile minimal
          pushd programs/charityblock
          rustup run 1.75.0 cargo generate-lockfile
          popd
          echo "Lockfile header:"
          head -n 3 programs/charityblock/Cargo.lock || true

      - name: Show toolchain
        shell: bash
        run: |
          set -eux
          rustup show
          cargo -V
          anchor --version
          solana --version

      - name: Build Program
        shell: bash
        env:
          RUSTUP_TOOLCHAIN: "1.86.0"
          ANCHOR_RUSTC_VERSION: "1.86.0"
        run: |
          set -eux
          $ANCHOR_BIN clean
          $ANCHOR_BIN build

      - name: Upload IDL and artifacts
        uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/idl/**
            target/deploy/**
            target/types/**