name: Build SBF
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # 1) Solana CLI (keeps our earlier fix)
      - name: Install Solana 1.18.20
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: "1.18.20"
          base_url: "https://release.anza.xyz"
          cache: true

      - name: Ensure Solana in PATH and show toolchain
        run: |
          set -eux
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          solana --version
          which cargo-build-sbf || true
          cargo-build-sbf --version || true

      # 2) Rust toolchain for building Anchor from source
      - name: Rust stable
        uses: dtolnay/rust-toolchain@stable

      # 3) System deps (present on runners, but ensure)
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      # 4) Anchor CLI via Cargo (no AVM script, no 404s)
      - name: Install Anchor CLI 0.31.1
        run: |
          set -eux
          cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 anchor-cli --locked
          anchor --version

      # 5) Build the program
      - name: Build Program
        env:
          ANCHOR_WALLET: ${{ github.workspace }}/target/deploy/charityblock-keypair.json
        run: |
          set -eux
          anchor clean
          anchor build
          ls -la target/deploy
          ls -la target/idl

      # 6) Publish build artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: charityblock-artifacts
          path: |
            target/deploy/charityblock.so
            target/deploy/charityblock-keypair.json
            target/idl/charityblock.json
